name = "Artifacts"
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[deps]
# What? Artifacts depends on Pkg?!  This is here so that we don't get warnings when we `Core.eval()`
# `Pkg` into the module to download lazy artifacts.
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
